### ISSUE TITLE
Une question

### ISSUE THREAD

**Issue by agneroalain** [pfmonville/Projet_etoile_2013_semestre2#1]
Salut je travaille sur la compression sans perte d'une chaine de caractère à tu des idées sur le sujet ! merci

**Comment by pfmonville** [comment]
Bonjour, si c'est juste pour compresser un chaîne de caractère ne contenant pas de caractère unicode (chaque caractère est codé par un seul octet de la table ASCII) alors un codage de Huffman est un bon début (https://fr.wikipedia.org/wiki/Codage_de_Huffman).

Sinon voici une survey sur la compression de chapine de caractère pour aller plus loin : https://www.informatik.uni-leipzig.de/~lohrey/12-SURVEY.pdf
